// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace HomeTask.Feature
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("SpecFlowFeature1")]
    public partial class SpecFlowFeature1Feature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "SpecFlowFeature1.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "SpecFlowFeature1", "\tIn order to avoid silly mistakes\r\n\tAs a math idiot\r\n\tI want to be told the sum o" +
                    "f two numbers", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("1. As User I want verify that main page is available just by https.")]
        public virtual void _1_AsUserIWantVerifyThatMainPageIsAvailableJustByHttps_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("1. As User I want verify that main page is available just by https.", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.Given("Not logged in user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
 testRunner.When("I enter http://omada.net page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 9
 testRunner.Then("I expect to be redirected to page https://www.omada.net/ with title Identity Mana" +
                    "gement | Omada Identity", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("2. As User I search gartner from home page and check search results")]
        public virtual void _2_AsUserISearchGartnerFromHomePageAndCheckSearchResults()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("2. As User I search gartner from home page and check search results", ((string[])(null)));
#line 12
this.ScenarioSetup(scenarioInfo);
#line 13
 testRunner.Given("User at home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 14
 testRunner.When("I search for gartner", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 15
 testRunner.Then("I expect to be redirected to page https://www.omada.net/en-us/search?q=gartner wi" +
                    "th title Search", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 16
 testRunner.And("I expect to see more than 1 search results", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 17
 testRunner.And("I expect to see There is Safety in Numbers title in these search results", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("3. As User navigate to search results page and check it")]
        public virtual void _3_AsUserNavigateToSearchResultsPageAndCheckIt()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("3. As User navigate to search results page and check it", ((string[])(null)));
#line 19
this.ScenarioSetup(scenarioInfo);
#line 20
 testRunner.Given("User at https://www.omada.net/en-us/search?q=gartner page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 21
 testRunner.When("Click on the link with text Gartner IAM Summit 2016 - London", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 22
 testRunner.Then("I expect to be at page with gartner-iam-summit-2016-london part in url", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 23
 testRunner.And("I expect to be at page with header type h1 contains string Gartner IAM Summit 201" +
                    "6 - London at least 1 times", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("4. As User navigate to news category and check")]
        [NUnit.Framework.TestCaseAttribute("240", "320", null)]
        [NUnit.Framework.TestCaseAttribute("842", "600", null)]
        [NUnit.Framework.TestCaseAttribute("843", "600", null)]
        [NUnit.Framework.TestCaseAttribute("1009", "600", null)]
        [NUnit.Framework.TestCaseAttribute("1010", "600", null)]
        public virtual void _4_AsUserNavigateToNewsCategoryAndCheck(string width, string height, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("4. As User navigate to news category and check", exampleTags);
#line 26
this.ScenarioSetup(scenarioInfo);
#line 27
 testRunner.Given("User at https://www.omada.net/en-us/more/news-events/news/gartner-iam-summit-2016" +
                    "-london page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 28
 testRunner.And(string.Format("User use browser window with {0}px X {1}px size", width, height), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 29
 testRunner.When("Click in breadcrumps block on the News", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 30
 testRunner.Then("I expect to be redirected to page https://www.omada.net/en-us/more/news-events/ne" +
                    "ws with title News | Omada Identity Suite", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 31
 testRunner.And("I expect to be at page with header type h1 contains string Gartner IAM Summit 201" +
                    "6 - London at least 1 times", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("5. As User navigate to homepage by click on logo")]
        public virtual void _5_AsUserNavigateToHomepageByClickOnLogo()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5. As User navigate to homepage by click on logo", ((string[])(null)));
#line 40
this.ScenarioSetup(scenarioInfo);
#line 41
 testRunner.Given("User at https://www.omada.net/en-us/more/news-events/news/gartner-iam-summit-2016" +
                    "-london page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 42
 testRunner.When("Click on the element logo at the top", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 43
 testRunner.Then("I expect to be redirected to page https://www.omada.net/en-us with title Identity" +
                    " Management | Omada Identity", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("6. As User navigate to homepage by click on EN language flag for desktop")]
        [NUnit.Framework.CategoryAttribute("Desktop")]
        public virtual void _6_AsUserNavigateToHomepageByClickOnENLanguageFlagForDesktop()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("6. As User navigate to homepage by click on EN language flag for desktop", new string[] {
                        "Desktop"});
#line 46
this.ScenarioSetup(scenarioInfo);
#line 47
 testRunner.Given("User at https://www.omada.net/en-us/more/news-events/news/gartner-iam-summit-2016" +
                    "-london page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 48
 testRunner.When("Click on the element EN language flag for desktop", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 49
 testRunner.Then("I expect to be redirected to page https://www.omada.net/en-us/omada-homepage with" +
                    " title Identity Management | Omada Identity", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("7. As User navigate to homepage by click on EN language flag for mobile")]
        [NUnit.Framework.CategoryAttribute("Mobile")]
        public virtual void _7_AsUserNavigateToHomepageByClickOnENLanguageFlagForMobile()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("7. As User navigate to homepage by click on EN language flag for mobile", new string[] {
                        "Mobile"});
#line 52
this.ScenarioSetup(scenarioInfo);
#line 53
 testRunner.Given("User at https://www.omada.net/en-us/more/news-events/news/gartner-iam-summit-2016" +
                    "-london page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 54
 testRunner.And("User use mobile browser window size", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 55
 testRunner.When("Click on the element mobile menu button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 56
 testRunner.And("Navigate to the element EN language flag for mobile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 57
 testRunner.And("Click on the element EN language flag for mobile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 58
 testRunner.Then("I expect to be redirected to page https://www.omada.net/en-us/omada-homepage with" +
                    " title Identity Management | Omada Identity", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("8. As desktop User navigate from home page to contact page and click tab and chec" +
            "k if there is class change on this element (take a screenshot of that)")]
        [NUnit.Framework.CategoryAttribute("Desktop")]
        [NUnit.Framework.TestCaseAttribute("U.S. West", null)]
        public virtual void _8_AsDesktopUserNavigateFromHomePageToContactPageAndClickTabAndCheckIfThereIsClassChangeOnThisElementTakeAScreenshotOfThat(string contactRegionButton, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Desktop"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("8. As desktop User navigate from home page to contact page and click tab and chec" +
                    "k if there is class change on this element (take a screenshot of that)", @__tags);
#line 62
this.ScenarioSetup(scenarioInfo);
#line 63
 testRunner.Given("User at home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 64
 testRunner.And("Click on the element Contacts button at the top desktop menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 65
 testRunner.When(string.Format("Click in contacts for desktop block on the {0}", contactRegionButton), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 66
 testRunner.Then(string.Format("Taking screenshot of the entire screen saved with name s8-{0}", contactRegionButton), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("9. As mobile User navigate from home to contact page and click tab and check if t" +
            "here is class change on this element (take a screenshot of that)")]
        [NUnit.Framework.CategoryAttribute("Mobile")]
        [NUnit.Framework.TestCaseAttribute("U.S. West", "240", "320", null)]
        [NUnit.Framework.TestCaseAttribute("U.S. East", "799", "600", null)]
        public virtual void _9_AsMobileUserNavigateFromHomeToContactPageAndClickTabAndCheckIfThereIsClassChangeOnThisElementTakeAScreenshotOfThat(string contactRegionButton, string width, string height, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Mobile"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("9. As mobile User navigate from home to contact page and click tab and check if t" +
                    "here is class change on this element (take a screenshot of that)", @__tags);
#line 72
this.ScenarioSetup(scenarioInfo);
#line 73
 testRunner.Given("User at home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 74
 testRunner.And(string.Format("User use browser window with {0}px X {1}px size", width, height), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 75
 testRunner.And("Click on the element mobile menu button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 76
 testRunner.And("Navigate to and click on the element contacts button in mobile menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 77
 testRunner.When(string.Format("Navigate to and click in contacts for mobile block on the {0}", contactRegionButton), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 78
 testRunner.Then(string.Format("Taking screenshot of the entire screen saved with name s9-{0}-{1}px_{2}px", contactRegionButton, width, height), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("10. As desktop User on contact page do a mouse hover on different location (take " +
            "a screenshot before and after performing the action)")]
        [NUnit.Framework.CategoryAttribute("Desktop")]
        [NUnit.Framework.TestCaseAttribute("U.S. West", "Denmark", null)]
        [NUnit.Framework.TestCaseAttribute("U.S. West", "U.S. East", null)]
        [NUnit.Framework.TestCaseAttribute("Denmark", "U.S. West", null)]
        [NUnit.Framework.TestCaseAttribute("U.S. West", "Germany", null)]
        [NUnit.Framework.TestCaseAttribute("U.S. West", "UK", null)]
        public virtual void _10_AsDesktopUserOnContactPageDoAMouseHoverOnDifferentLocationTakeAScreenshotBeforeAndAfterPerformingTheAction(string contactRegionButtonStart, string contactRegionButtonSwitchTo, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Desktop"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("10. As desktop User on contact page do a mouse hover on different location (take " +
                    "a screenshot before and after performing the action)", @__tags);
#line 85
this.ScenarioSetup(scenarioInfo);
#line 86
 testRunner.Given("User at contact page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 87
 testRunner.And(string.Format("Click in contacts for desktop block on the {0}", contactRegionButtonStart), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 88
 testRunner.And(string.Format("Taking screenshot of the entire screen saved with name s10-{0}-to-{1}-before", contactRegionButtonStart, contactRegionButtonSwitchTo), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 89
 testRunner.When(string.Format("Click in contacts for desktop block on the {0}", contactRegionButtonSwitchTo), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 90
 testRunner.Then(string.Format("Taking screenshot of the entire screen saved with name s10-{0}-to-{1}-after", contactRegionButtonStart, contactRegionButtonSwitchTo), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("11. Open Read Privacy Policy in another tab. Check if it is opened and loaded pro" +
            "perly")]
        [NUnit.Framework.CategoryAttribute("Desktop")]
        public virtual void _11_OpenReadPrivacyPolicyInAnotherTab_CheckIfItIsOpenedAndLoadedProperly()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("11. Open Read Privacy Policy in another tab. Check if it is opened and loaded pro" +
                    "perly", new string[] {
                        "Desktop"});
#line 100
this.ScenarioSetup(scenarioInfo);
#line 101
 testRunner.Given("User at contact page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 102
 testRunner.When("Open Privacy Policy at the bottom cookiebar in new tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 103
 testRunner.Then("I expect to be at page with title Omada | Processing of Personal Data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 104
 testRunner.And("I expect to be at page with h1 header WEBSITE PRIVACY POLICY", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 105
 testRunner.And("I expect to be at page with text info@omada.net", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("12. Open Privacy Policy in another tab. Check if it is opened and loaded properly" +
            "")]
        [NUnit.Framework.CategoryAttribute("Desktop")]
        public virtual void _12_OpenPrivacyPolicyInAnotherTab_CheckIfItIsOpenedAndLoadedProperly()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("12. Open Privacy Policy in another tab. Check if it is opened and loaded properly" +
                    "", new string[] {
                        "Desktop"});
#line 108
this.ScenarioSetup(scenarioInfo);
#line 109
 testRunner.Given("User at contact page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 110
 testRunner.When("Open Privacy Policy at the footer in new tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 111
 testRunner.Then("I expect to be at page with title Omada | Processing of Personal Data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 112
 testRunner.And("I expect to be at page with h1 header WEBSITE PRIVACY POLICY", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 113
 testRunner.And("I expect to be at page with text info@omada.net", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("13. Open Privacy Policy in another tab. Check if it is opened and loaded properly" +
            "")]
        [NUnit.Framework.CategoryAttribute("Desktop")]
        public virtual void _13_OpenPrivacyPolicyInAnotherTab_CheckIfItIsOpenedAndLoadedProperly()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("13. Open Privacy Policy in another tab. Check if it is opened and loaded properly" +
                    "", new string[] {
                        "Desktop"});
#line 116
this.ScenarioSetup(scenarioInfo);
#line 117
 testRunner.Given("User at contact page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 118
 testRunner.And("Privacy Policy at the bottom cookiebar opened in new tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 119
 testRunner.And("User at the first tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 120
 testRunner.When("Click on the element close cookies button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 121
 testRunner.And("Close second tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 122
 testRunner.And("User switch to the first tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 123
 testRunner.And("Click on the element logo at the top", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 124
 testRunner.Then("I expect that element close cookies button is not displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("14. From the bottom of the Home page choose Cases link. On new open clickDownload" +
            " PDF button. Fill necessary data to download PDF file.")]
        [NUnit.Framework.CategoryAttribute("Desktop")]
        [NUnit.Framework.TestCaseAttribute("1", null)]
        [NUnit.Framework.TestCaseAttribute("2", null)]
        [NUnit.Framework.TestCaseAttribute("3", null)]
        [NUnit.Framework.TestCaseAttribute("4", null)]
        [NUnit.Framework.TestCaseAttribute("5", null)]
        [NUnit.Framework.TestCaseAttribute("6", null)]
        [NUnit.Framework.TestCaseAttribute("7", null)]
        [NUnit.Framework.TestCaseAttribute("8", null)]
        [NUnit.Framework.TestCaseAttribute("9", null)]
        [NUnit.Framework.TestCaseAttribute("10", null)]
        [NUnit.Framework.TestCaseAttribute("11", null)]
        [NUnit.Framework.TestCaseAttribute("12", null)]
        [NUnit.Framework.TestCaseAttribute("13", null)]
        [NUnit.Framework.TestCaseAttribute("14", null)]
        [NUnit.Framework.TestCaseAttribute("15", null)]
        [NUnit.Framework.TestCaseAttribute("16", null)]
        public virtual void _14_FromTheBottomOfTheHomePageChooseCasesLink_OnNewOpenClickDownloadPDFButton_FillNecessaryDataToDownloadPDFFile_(string number, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Desktop"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("14. From the bottom of the Home page choose Cases link. On new open clickDownload" +
                    " PDF button. Fill necessary data to download PDF file.", @__tags);
#line 127
this.ScenarioSetup(scenarioInfo);
#line 128
 testRunner.Given("User at home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 129
 testRunner.And("Click on the element close cookies button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 130
 testRunner.And("Navigate to and click on the element Cases button at the footer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 131
 testRunner.When(string.Format("Navigate to and click in Omada Customers number number {0} on the Download PDF", number), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 132
 testRunner.And("Fill cases form field jobtitle with text Test Job Title", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 133
 testRunner.And("Fill cases form field firstname with text Test First Name", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 134
 testRunner.And("Fill cases form field lastname with text Test Last Name", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 135
 testRunner.And("Fill cases form field emailaddress1 with text andriistepura+omada-test14@gmail.co" +
                    "m", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 136
 testRunner.And("Fill cases form field telephone1 with text +48 889 417 715", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 137
 testRunner.And("Fill cases form field parentcustomerid with text W2BUSINESS Sp. z O.o", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 138
 testRunner.And("Select cases form selector address1_county option Poland", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 139
 testRunner.And("Check checkbox newsletter accept checkbox", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 140
 testRunner.And("Unlock slider captcha if exists for 100%", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 141
 testRunner.And("Click on the element unlocked Download PDF button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 142
 testRunner.Then("I expect to be at page with download-case part in url", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 143
 testRunner.And("I expect to be at page with h1 header Thank You for Your Request", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 144
 testRunner.And("I expect to be at page with text Download Customer Case:", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 145
 testRunner.When("Click on the element Download Customer Case link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 146
 testRunner.And("File with name .pdf downloaded to you local machine", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
