// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace HomeTask.Feature
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("SpecFlowFeature1")]
    public partial class SpecFlowFeature1Feature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "SpecFlowFeature1.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "SpecFlowFeature1", "\tIn order to avoid silly mistakes\r\n\tAs a math idiot\r\n\tI want to be told the sum o" +
                    "f two numbers", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("As User I want verify that main page is available just by https.")]
        public virtual void AsUserIWantVerifyThatMainPageIsAvailableJustByHttps_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("As User I want verify that main page is available just by https.", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.Given("Not logged in user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
 testRunner.When("I enter http://omada.net page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 9
 testRunner.Then("I expect to be redirected to page https://www.omada.net/ with title Identity Mana" +
                    "gement | Omada Identity", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("As User I search gartner from home page and check search results")]
        public virtual void AsUserISearchGartnerFromHomePageAndCheckSearchResults()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("As User I search gartner from home page and check search results", ((string[])(null)));
#line 12
this.ScenarioSetup(scenarioInfo);
#line 13
 testRunner.Given("User at home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 14
 testRunner.When("I search for gartner", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 15
 testRunner.Then("I expect to be redirected to page https://www.omada.net/en-us/search?q=gartner wi" +
                    "th title Search", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 16
 testRunner.And("I expect to see more than 1 search results", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 17
 testRunner.And("I expect to see There is Safety in Numbers title in these search results", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("As User navigate to search results page and check it")]
        public virtual void AsUserNavigateToSearchResultsPageAndCheckIt()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("As User navigate to search results page and check it", ((string[])(null)));
#line 19
this.ScenarioSetup(scenarioInfo);
#line 20
 testRunner.Given("User at https://www.omada.net/en-us/search?q=gartner page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 21
 testRunner.When("Click on the link with text Gartner IAM Summit 2016 - London", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 22
 testRunner.Then("I expect to be at page with gartner-iam-summit-2016-london part in url", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 23
 testRunner.And("I expect to be at page with header type h1 contains string Gartner IAM Summit 201" +
                    "6 - London at least 1 times", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("As User navigate to news category and check")]
        [NUnit.Framework.TestCaseAttribute("240", "320", null)]
        [NUnit.Framework.TestCaseAttribute("842", "600", null)]
        [NUnit.Framework.TestCaseAttribute("843", "600", null)]
        [NUnit.Framework.TestCaseAttribute("1009", "600", null)]
        [NUnit.Framework.TestCaseAttribute("1010", "600", null)]
        public virtual void AsUserNavigateToNewsCategoryAndCheck(string width, string height, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("As User navigate to news category and check", exampleTags);
#line 26
this.ScenarioSetup(scenarioInfo);
#line 27
 testRunner.Given("User at https://www.omada.net/en-us/more/news-events/news/gartner-iam-summit-2016" +
                    "-london page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 28
 testRunner.And(string.Format("User use browser window with {0}px X {1}px size", width, height), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 29
 testRunner.When("Click in breadcrumps block on the link with text News", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 30
 testRunner.Then("I expect to be redirected to page https://www.omada.net/en-us/more/news-events/ne" +
                    "ws with title News | Omada Identity Suite", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 31
 testRunner.And("I expect to be at page with header type h1 contains string Gartner IAM Summit 201" +
                    "6 - London at least 1 times", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("As User navigate to homepage by click on logo")]
        public virtual void AsUserNavigateToHomepageByClickOnLogo()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("As User navigate to homepage by click on logo", ((string[])(null)));
#line 40
this.ScenarioSetup(scenarioInfo);
#line 41
 testRunner.Given("User at https://www.omada.net/en-us/more/news-events/news/gartner-iam-summit-2016" +
                    "-london page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 42
 testRunner.When("Click on the element logo at the top", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 43
 testRunner.Then("I expect to be redirected to page https://www.omada.net/en-us with title Identity" +
                    " Management | Omada Identity", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("As User navigate to homepage by click on EN language flag for desktop")]
        [NUnit.Framework.CategoryAttribute("Desktop")]
        public virtual void AsUserNavigateToHomepageByClickOnENLanguageFlagForDesktop()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("As User navigate to homepage by click on EN language flag for desktop", new string[] {
                        "Desktop"});
#line 46
this.ScenarioSetup(scenarioInfo);
#line 47
 testRunner.Given("User at https://www.omada.net/en-us/more/news-events/news/gartner-iam-summit-2016" +
                    "-london page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 48
 testRunner.When("Click on the element EN language flag for desktop", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 49
 testRunner.Then("I expect to be redirected to page https://www.omada.net/en-us/omada-homepage with" +
                    " title Identity Management | Omada Identity", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("As User navigate to homepage by click on EN language flag for mobile")]
        [NUnit.Framework.CategoryAttribute("Mobile")]
        public virtual void AsUserNavigateToHomepageByClickOnENLanguageFlagForMobile()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("As User navigate to homepage by click on EN language flag for mobile", new string[] {
                        "Mobile"});
#line 52
this.ScenarioSetup(scenarioInfo);
#line 53
 testRunner.Given("User at https://www.omada.net/en-us/more/news-events/news/gartner-iam-summit-2016" +
                    "-london page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 54
 testRunner.And("User use mobile browser window size", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 55
 testRunner.When("Click on the element mobile menu button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 56
 testRunner.And("Navigate to the element EN language flag for mobile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 57
 testRunner.And("Click on the element EN language flag for mobile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 58
 testRunner.Then("I expect to be redirected to page https://www.omada.net/en-us/omada-homepage with" +
                    " title Identity Management | Omada Identity", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("As User navigate from home page to contact page and click U.S West and check if t" +
            "here is class change on this element (take a screenshot of that)")]
        [NUnit.Framework.CategoryAttribute("Desktop")]
        public virtual void AsUserNavigateFromHomePageToContactPageAndClickU_SWestAndCheckIfThereIsClassChangeOnThisElementTakeAScreenshotOfThat()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("As User navigate from home page to contact page and click U.S West and check if t" +
                    "here is class change on this element (take a screenshot of that)", new string[] {
                        "Desktop"});
#line 61
this.ScenarioSetup(scenarioInfo);
#line 62
 testRunner.Given("User at home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 63
 testRunner.And("Click on the element Contacts button at the top desktop menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 64
 testRunner.And("Taking screenshot of the entire screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 65
 testRunner.When("Click on the element EN language flag for desktop", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 66
 testRunner.Then("I expect to be redirected to page https://www.omada.net/en-us/omada-homepage with" +
                    " title Identity Management | Omada Identity", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
